### ISSUE TITLE
Error in pyWGCNA dependences

### ISSUE THREAD

**Issue by lmigueel** [mortazavilab/PyWGCNA#21]
Hi!
I installed pyWGCNA, but it showed a dependency error on numpy package and the MachAr class when I load it using "import pyWGNA". Looking at numpy updates, this class has been deprecated in version 1.22 (https://numpy.org/devdocs/release/1.22.0-notes.html), the most current being version 1.24.

Would you have any solution?

Thanks.

Error message: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11288/4062357097.py in <module>
----> 1 import PyWGCNA

~\anaconda3\lib\site-packages\PyWGCNA\__init__.py in <module>
----> 1 from PyWGCNA.wgcna import *
      2 from PyWGCNA.utils import *
      3 from PyWGCNA.geneExp import *
      4 from PyWGCNA.comparison import *

~\anaconda3\lib\site-packages\PyWGCNA\wgcna.py in <module>
     11 from scipy.cluster.hierarchy import linkage, cut_tree, dendrogram, fcluster
     12 from scipy.stats import t
---> 13 from statsmodels.formula.api import ols
     14 import resource
     15 from matplotlib import colors as mcolors

~\anaconda3\lib\site-packages\statsmodels\formula\api.py in <module>
----> 1 import statsmodels.regression.linear_model as lm_
      2 import statsmodels.discrete.discrete_model as dm_
      3 import statsmodels.regression.mixed_linear_model as mlm_
      4 import statsmodels.genmod.generalized_linear_model as glm_
      5 import statsmodels.robust.robust_linear_model as roblm_

~\anaconda3\lib\site-packages\statsmodels\regression\__init__.py in <module>
----> 1 from .linear_model import yule_walker
      2 
      3 from statsmodels.tools._testing import PytestTester
      4 
      5 __all__ = ['yule_walker', 'test']

~\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py in <module>
     44 from statsmodels.tools.decorators import (cache_readonly,
     45                                           cache_writable)
---> 46 import statsmodels.base.model as base
     47 import statsmodels.base.wrapper as wrap
     48 from statsmodels.emplike.elregress import _ELRegOpts

~\anaconda3\lib\site-packages\statsmodels\base\model.py in <module>
     14                                           cached_value, cached_data)
     15 import statsmodels.base.wrapper as wrap
---> 16 from statsmodels.tools.numdiff import approx_fprime
     17 from statsmodels.tools.sm_exceptions import ValueWarning, \
     18     HessianInversionWarning

~\anaconda3\lib\site-packages\statsmodels\tools\numdiff.py in <module>
     49 
     50 # NOTE: we only do double precision internally so far
---> 51 EPS = np.MachAr().eps
     52 
     53 _hessian_docs = """

~\anaconda3\lib\site-packages\numpy\__init__.py in __getattr__(attr)
    282             return Tester
    283 
--> 284         raise AttributeError("module {!r} has no attribute "
    285                              "{!r}".format(__name__, attr))
    286 

AttributeError: module 'numpy' has no attribute 'MachAr'

**Comment by tyaoi** [comment]
Hi, lmigueel

Try the following steps to create a virtual environment for conda.

`conda create -n your_env python=3.9 scipy` 
`conda activate your_env` 

After activating the env, Git cloning the PyWGCNA repository, going to the PyWGCNA directory.

Modify comparison.py as shown in the following comment. 
https://github.com/mortazavilab/PyWGCNA/issues/18#issuecomment-1407446255

Then, run.

`python setup.py install`

So far, as far as I have tried, enrichment analysis is working well with gseapy version 0.10.5.

`pip unistall gseapy` 
`pip install gseapy=0.10.5`


tyaoi

**Comment by nargesr** [comment]
Hi,

For now, please downgrade your numpy package. 
Meanwhile, I'm looking to find a replacement for statsmodels package or to see if they're going to update their package

**Comment by nargesr** [comment]
Hi,

There is a [new version of statsmodels](https://github.com/statsmodels/statsmodels/releases/tag/v0.14.0) that is compatible with the new version of NumPy. 
I updated the requirements which hopefully fixed this issue.

Please do not hesitate to reopen this issue if you get the same error!
